package models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import dynamo.TableConstants;
import lombok.Getter;
import lombok.Setter;

@DynamoDBTable(tableName=TableConstants.EXAMPLE_TABLE_NAME)
public class DynamoDBItem {
    @Getter
    @Setter
    @DynamoDBHashKey(attributeName= TableConstants.EXAMPLE_TABLE_ID)
    @DynamoDBAutoGeneratedKey
    private String itemId;
}
